
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TournamentManagementConsoleUi.View.Dialogs {
    using System;
    using Terminal.Gui;
    
    
    public partial class CreateTeamDialog : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextField nameTextField;
        
        private Terminal.Gui.Button addTeamBtn;
        
        private void InitializeComponent() {
            this.addTeamBtn = new Terminal.Gui.Button();
            this.nameTextField = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.Width = Dim.Percent(78f);
            this.Height = Dim.Percent(43f);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Modal = true;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Add Team";
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 0;
            this.label.Y = 0;
            this.label.Data = "label";
            this.label.Text = "Name";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.nameTextField.Width = Dim.Fill(10);
            this.nameTextField.Height = 1;
            this.nameTextField.X = 5;
            this.nameTextField.Y = 0;
            this.nameTextField.Secret = false;
            this.nameTextField.Data = "nameTextField";
            this.nameTextField.Text = "";
            this.nameTextField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.nameTextField);
            this.addTeamBtn.Width = 12;
            this.addTeamBtn.Height = 1;
            this.addTeamBtn.X = Pos.Center();
            this.addTeamBtn.Y = 4;
            this.addTeamBtn.Data = "addTeamBtn";
            this.addTeamBtn.Text = "Add Team";
            this.addTeamBtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.addTeamBtn.IsDefault = false;
            this.Add(this.addTeamBtn);
        }
    }
}
