
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TournamentManagementConsoleUi.View {
    using System;
    using Terminal.Gui;
    
    
    public partial class MatchView : Terminal.Gui.View {
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.Label firstTeamLabel;
        
        private Terminal.Gui.Label secondTeamLabel;
        
        private Terminal.Gui.Button editBtn;
        
        private void InitializeComponent() {
            this.editBtn = new Terminal.Gui.Button();
            this.secondTeamLabel = new Terminal.Gui.Label();
            this.firstTeamLabel = new Terminal.Gui.Label();
            this.frameView = new Terminal.Gui.FrameView();
            this.Width = 20;
            this.Height = 6;
            this.X = 0;
            this.Y = 0;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Width = 20;
            this.frameView.Height = 6;
            this.frameView.X = 0;
            this.frameView.Y = 0;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.BorderBrush = Terminal.Gui.Color.BrightGreen;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "";
            this.Add(this.frameView);
            this.firstTeamLabel.Width = 20;
            this.firstTeamLabel.Height = 1;
            this.firstTeamLabel.X = 0;
            this.firstTeamLabel.Y = 0;
            this.firstTeamLabel.Data = "firstTeamLabel";
            this.firstTeamLabel.Text = "First Team";
            this.firstTeamLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Add(this.firstTeamLabel);
            this.secondTeamLabel.Width = 20;
            this.secondTeamLabel.Height = 1;
            this.secondTeamLabel.X = 0;
            this.secondTeamLabel.Y = 1;
            this.secondTeamLabel.Data = "secondTeamLabel";
            this.secondTeamLabel.Text = "Second Team";
            this.secondTeamLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Add(this.secondTeamLabel);
            this.editBtn.Width = 20;
            this.editBtn.Height = 1;
            this.editBtn.X = 0;
            this.editBtn.Y = 3;
            this.editBtn.Data = "editBtn";
            this.editBtn.Text = "Edit";
            this.editBtn.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.editBtn.IsDefault = false;
            this.frameView.Add(this.editBtn);
        }
    }
}
