
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TournamentManagementConsoleUi.View.Windows {
    using System;
    using Terminal.Gui;
    
    
    public partial class TorunamentsListWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.ListView tournamentsListView;
        
        private Terminal.Gui.Button openTournamentBtn;
        
        private Terminal.Gui.Button createTournamentBtn;
        
        private void InitializeComponent() {
            this.createTournamentBtn = new Terminal.Gui.Button();
            this.openTournamentBtn = new Terminal.Gui.Button();
            this.tournamentsListView = new Terminal.Gui.ListView();
            this.label = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = true;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Tournament Management App (Press Ctrl+Q to quit)";
            this.label.Width = 3;
            this.label.Height = 1;
            this.label.X = Pos.Center();
            this.label.Y = 2;
            this.label.Data = "label";
            this.label.Text = "Tournaments";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.tournamentsListView.Width = 20;
            this.tournamentsListView.Height = 10;
            this.tournamentsListView.X = Pos.Center();
            this.tournamentsListView.Y = Pos.Bottom(label) + 1;
            this.tournamentsListView.Data = "tournamentsListView";
            this.tournamentsListView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tournamentsListView.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.tournamentsListView.AllowsMarking = false;
            this.tournamentsListView.AllowsMultipleSelection = true;
            this.Add(this.tournamentsListView);
            this.openTournamentBtn.Width = 19;
            this.openTournamentBtn.Height = 1;
            this.openTournamentBtn.X = Pos.Center();
            this.openTournamentBtn.Y = Pos.Bottom(tournamentsListView) + 1;
            this.openTournamentBtn.Data = "openTournamentBtn";
            this.openTournamentBtn.Text = "Open Tournament";
            this.openTournamentBtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.openTournamentBtn.IsDefault = false;
            this.Add(this.openTournamentBtn);
            this.createTournamentBtn.Width = 21;
            this.createTournamentBtn.Height = 1;
            this.createTournamentBtn.X = Pos.Center();
            this.createTournamentBtn.Y = Pos.Bottom(openTournamentBtn) + 1;
            this.createTournamentBtn.Data = "createTournamentBtn";
            this.createTournamentBtn.Text = "Create Tournament";
            this.createTournamentBtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.createTournamentBtn.IsDefault = false;
            this.Add(this.createTournamentBtn);
        }
    }
}
