
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TournamentManagementConsoleUi.View.Windows {
    using System;
    using Terminal.Gui;
    
    
    public partial class TournamentWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Label gameNameLabel;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.Label descriptionLabel;
        
        private Terminal.Gui.ScrollView ladderScrollView;
        
        private Terminal.Gui.Button deleteTournamentBtn;
        
        private void InitializeComponent() {
            this.deleteTournamentBtn = new Terminal.Gui.Button();
            this.ladderScrollView = new Terminal.Gui.ScrollView();
            this.descriptionLabel = new Terminal.Gui.Label();
            this.label2 = new Terminal.Gui.Label();
            this.gameNameLabel = new Terminal.Gui.Label();
            this.label = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = true;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Tournament Name (Press Ctrl+Q to go back)";
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 0;
            this.label.Y = 0;
            this.label.Data = "label";
            this.label.Text = "Game:";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.gameNameLabel.Width = Dim.Fill(8);
            this.gameNameLabel.Height = 1;
            this.gameNameLabel.X = 6;
            this.gameNameLabel.Y = 0;
            this.gameNameLabel.Data = "gameNameLabel";
            this.gameNameLabel.Text = "Name";
            this.gameNameLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.gameNameLabel);
            this.label2.Width = 3;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 2;
            this.label2.Data = "label2";
            this.label2.Text = "Description:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.descriptionLabel.Width = Dim.Fill(8);
            this.descriptionLabel.Height = 1;
            this.descriptionLabel.X = 13;
            this.descriptionLabel.Y = 2;
            this.descriptionLabel.Data = "descriptionLabel";
            this.descriptionLabel.Text = "lorem ipsum";
            this.descriptionLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.descriptionLabel);
            this.ladderScrollView.Width = Dim.Fill(0);
            this.ladderScrollView.Height = 20;
            this.ladderScrollView.X = 0;
            this.ladderScrollView.Y = Pos.Bottom(label2) + 1;
            this.ladderScrollView.ContentSize = new Size(1000,2000);
            this.ladderScrollView.Data = "ladderScrollView";
            this.ladderScrollView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.ladderScrollView);
            this.deleteTournamentBtn.Width = 21;
            this.deleteTournamentBtn.Height = 1;
            this.deleteTournamentBtn.X = 19;
            this.deleteTournamentBtn.Y = 25;
            this.deleteTournamentBtn.Data = "deleteTournamentBtn";
            this.deleteTournamentBtn.Text = "Delete Tournament";
            this.deleteTournamentBtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.deleteTournamentBtn.IsDefault = false;
            this.Add(this.deleteTournamentBtn);
        }
    }
}
