
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TournamentManagementConsoleUi.View.Windows {
    using Terminal.Gui;
    
    
    public partial class TournamentWindow {
        
        public TournamentWindow() {
            InitializeComponent();
        }
    }
}
